export const AREAS = [
  { key: "shibuya", label: "渋谷" },
  { key: "shinjuku", label: "新宿" },
  { key: "roppongi", label: "六本木" },
  { key: "ebisu", label: "恵比寿" },
  { key: "ginza", label: "銀座" },
  { key: "ikebukuro", label: "池袋" },
  { key: "nakameguro", label: "中目黒" },
  { key: "daikanyama", label: "代官山" },
  { key: "omotesando", label: "表参道" },
  { key: "akasaka", label: "赤坂" },
  { key: "akihabara", label: "秋葉原" },
  { key: "ueno", label: "上野" },
  { key: "other", label: "その他" },
];